Added table component, not finished
MartinezBaker/crypto-app pull request #2
Opened 2022-03-08 16:10 UTC by MartinezBaker

Reverted back to using table elements.. the problem with the expanding progress bar was more than likely coming from the progress bar component it's self. I switched the sizing of the parent div from width: "100%" to width: "190px". I believed this helped because from what I could see the sizing of the parent div was dependent on the size of the table cell, and the size of the table cell was dependent on its contents, giving the progress bar no real boundaries, so by setting it to a fixed width it seemed to fix the problem. Once again sizing and spacing isn't set in stone, these are just 'raw renders'.

2022-03-11 20:39 UTC, MartinezBaker commented
Made requested changes

2022-03-13 01:57 UTC, yoloOnTheBattlefield requested changes

2022-03-13 01:57 UTC, yoloOnTheBattlefield commented on crypto-app/src/components/CoinInstance/CoinInstance.js
> +import {formatTimePercent, formatNum} from '../../utils/index';
import {` `formatTimePercent, formatNum` `} from '../../utils/index';

2022-03-13 01:57 UTC, yoloOnTheBattlefield commented on crypto-app/src/components/CoinInstance/CoinInstance.js
> +      {props.name.length < 9 ? props.name : props.name.slice(0, 9) + "..."} (
you could make an utility function here

2022-03-13 01:57 UTC, yoloOnTheBattlefield commented on crypto-app/src/components/CoinInstance/styles.js
> +  color: ${(props) => {
you can destructure here ({ data })

2022-03-13 01:57 UTC, yoloOnTheBattlefield commented on crypto-app/src/pages/Coins/Coins.js
> +import axios from 'axios';
npm modules come before your components

2022-03-13 01:57 UTC, yoloOnTheBattlefield commented on crypto-app/src/pages/Coins/Coins.js
> +        `https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=50&page=${this.state.page}&sparkline=true&price_change_percentage=1h%2C24h%2C7d`
this.state.page in your query will be the previous page, not the one you setup in the beginning FYI

2022-03-13 01:57 UTC, yoloOnTheBattlefield commented on crypto-app/src/pages/Coins/Coins.js
> +            hasMore={true}
what if you get to the bottom?

2022-03-13 01:57 UTC, yoloOnTheBattlefield commented on crypto-app/src/pages/Coins/Coins.js
> +                    }
`oneHour={coin.price_change_percentage_1h_in_currency?.toString()}`

this might help

2022-03-15 09:43 UTC, yoloOnTheBattlefield requested changes

2022-03-15 09:43 UTC, yoloOnTheBattlefield commented on crypto-app/src/components/index.js
> +export {default as CoinInstance} from './CoinInstance'
export {` `default as CoinInstance` `} from './CoinInstance'

2022-03-15 09:43 UTC, yoloOnTheBattlefield commented on crypto-app/src/pages/CoinPage/index.js
> +export {default} from './CoinPage'
export {` `default` `} from './CoinPage'

2022-03-16 15:42 UTC, merged